### ISSUE TITLE
pypi package shogun

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3132]
this should be super easy with setuptools.
ping me (@vigsterkr) for help

**Comment by karlnapf** [comment]
`pip install shogun`

**Comment by vigsterkr** [comment]
for the record: this is a good tool to call cmake from `setup.py`: https://github.com/scikit-build/scikit-build

**Comment by Eejya** [comment]
@karlnapf @vigsterkr Please have a look at a simple setup.py https://github.com/Eejya/shogun/blob/pip_install/setup.py I've written. I've not tested it completely due to a make error I keep getting - http://pastebin.com/vPNh4XPa. Any pointers on how to fix the error ?

**Comment by karlnapf** [comment]
@arianepaola another one for you, you could in fact build things on the gist above
@Eejya I don't really get the error you are having there. Does this also occur when you compile Shogun normally?

**Comment by arianepaola** [comment]
@karlnapf ok, I will have a look.

**Comment by karlnapf** [comment]
Done since 2151b9c8cce2aca068a421460e580d8c5d398293

**Comment by vigsterkr** [comment]
this is still broken. let's keep it open... in the meanwhile you can install shogun python interface with conda:
``` conda install -c conda-forge shogun ```
